/* This file is auto-generated by @tanstack/router. I'm providing a static version for initial scaffold. */
import { Route as rootRoute } from './routes/__root';
import { createRouter } from '@tanstack/react-router';

export const routeTree = rootRoute.addChildren([]);

export const router = createRouter({ routeTree });
